### ISSUE TITLE
Feature request: maintain aspect ratio on SHIFT key

### ISSUE THREAD

**Issue by ergunozyurt** [thegreatercurve/react-simple-crop#1]
The SHIFT key has been the standard way of keeping the aspect ratio of selection on transformations and would be good to have that feature on crop selector. 

Thanks!

**Comment by thegreatercurve** [comment]
@ergunozyurt Added this to the `TODO` list via [02174cc](https://github.com/thegreatercurve/react-simple-crop/commit/02174ccf6ee5daad78541338d7aebd82c5b865a3).
